<a href="https://colab.research.google.com/github/Aviz22/1.1_Preco_Gasolina_Brasil/blob/main/Pre%C3%A7oGasoBrasil.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

#####1. Carregando os conjuntos de dados "gasolina_2000+csv" e "gasolina_2010+csv" em dois DataFrames diferentes e combinando-os em um único DataFrame

In [2]:
df1 = pd.read_csv("/content/gasolina_2000+.csv", index_col=0)
df2 = pd.read_csv("/content/gasolina_2010+.csv", index_col=0)

#Juntando os dois
df = pd.concat([df1, df2])

<ipython-input-2-0c275edad890>:2: DtypeWarning: Columns (12,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("/content/gasolina_2010+.csv", index_col=0)

In [3]:
df1.shape

(42638, 18)

In [4]:
df2.shape

(78185, 18)

In [5]:
df.shape

(120823, 18)

#####2. Investigar as colunas e entendendo o conjunto de dados, usando o head() e info()

In [6]:
df.tail()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  object
 1   DATA FINAL                     120823 non-null  object
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: float64(5), int64(1), object(12)
memory usage: 17.5+ MB

#####3. Selecionar a terceira entrada da coluna DATA INICIAL e verificar seu tipo

In [8]:
type(df["DATA INICIAL"] [2])

str

#####4. As colunas DATA INICIAL e DATA FINAL estão formatadas como string. Utilizando o método pd.to_datetime(), converter ambas colunas para Timestamp/Datetime

In [9]:
df["DATA INICIAL"] = pd.to_datetime(df["DATA INICIAL"])
df["DATA FINAL"] = pd.to_datetime(df["DATA FINAL"])
type(df["DATA FINAL"].iloc[2])

pandas._libs.tslibs.timestamps.Timestamp

#####5. Criar uma nova coluna para representar o ano e o mês(aaaa-mm), utilizando a coluna DATA FINAL como referência

In [10]:
# Formatação padão para datas - Ano-Mes
df["ANO-MES"] = df["DATA FINAL"].apply(lambda x: '{}'.format(x.year)) + df["DATA FINAL"].apply(lambda x: '-{:02d}'.format(x.month))

In [11]:
df["ANO-MES"]

0         2004-05
1         2004-05
2         2004-05
3         2004-05
4         2004-05
           ...
120818    2021-05
120819    2021-05
120820    2021-05
120821    2021-05
120822    2021-05
Name: ANO-MES, Length: 120823, dtype: object

#####6. Utilizando o value_counts(), e listando os tipos de produtos contidos na base de dados

In [12]:
df.columns

Index(['DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO', 'PRODUTO',
       'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO',
       'ANO-MES'],
      dtype='object')

In [13]:
df["PRODUTO"].value_counts()

GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: PRODUTO, dtype: int64

#####7. Filtrar o DateFrame para obter apenas dados da 'GASOLINA COMUM'. Gravando em uma nova variável

In [14]:
df_filtro = df['PRODUTO'] == 'GASOLINA COMUM'
df2 = df[df_filtro]
df2

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO-MES
12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.990,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,2004-05
12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.850,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,2004-05
12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.000,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,2004-05
12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.970,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,2004-05
12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.000,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024,2004-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120721,2021-04-25,2021-05-01,NORTE,RORAIMA,GASOLINA COMUM,12,R$/l,5.364,0.065,5.310,5.530,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120722,2021-04-25,2021-05-01,SUL,SANTA CATARINA,GASOLINA COMUM,119,R$/l,5.051,0.251,4.640,5.599,-99999.0,0.050,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120724,2021-04-25,2021-05-01,NORDESTE,SERGIPE,GASOLINA COMUM,34,R$/l,5.586,0.088,5.410,5.699,-99999.0,0.016,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120725,2021-04-25,2021-05-01,NORTE,TOCANTINS,GASOLINA COMUM,20,R$/l,5.751,0.160,5.578,6.119,-99999.0,0.028,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05

#####8. Qual o preço médio de revenda da gasolina em agosto de 2008?

In [15]:
df2[df2['ANO-MES'] == '2008-08'] ["PREÇO MÉDIO REVENDA"].mean()

2.6012444444444442

#####9. Preço médio de revenda da gasolina em Maio de 2014 em São Paulo?

In [16]:
df2[(df2['ANO-MES'] == '2014-05') & (df2['ESTADO'] == 'SAO PAULO')] ["PREÇO MÉDIO REVENDA"].mean()

2.8822

#####10. Em qual(quais) estado(s) a gasolina ultrapassou a barreira dos R$ 5,00? E quando isso ocorreu?

In [17]:
df2[df2["PREÇO MÉDIO REVENDA"] > 5] [["ESTADO", "ANO-MES", "PREÇO MÉDIO REVENDA"]].head(20)

                ESTADO  ANO-MES  PREÇO MÉDIO REVENDA
98201             ACRE  2018-05                5.053
98347             ACRE  2018-06                5.035
98493             ACRE  2018-06                5.038
98511   RIO DE JANEIRO  2018-06                5.016
98646             ACRE  2018-06                5.031
98797             ACRE  2018-06                5.036
98948             ACRE  2018-06                5.039
99098             ACRE  2018-07                5.021
99247             ACRE  2018-07                5.042
99398             ACRE  2018-07                5.038
99549             ACRE  2018-07                5.033
99701             ACRE  2018-08                5.031
99852             ACRE  2018-08                5.015
100003            ACRE  2018-08                5.023
100153            ACRE  2018-08                5.036
100302            ACRE  2018-09                5.018
100453            ACRE  2018-09                5.074
100604            ACRE  2018-09                5.129
100756            ACRE  2018-09                5.153
100774  RIO DE JANEIRO  2018-09                5.036

#####11. Qual a média de preço dos estados da região sul em 2012?

In [18]:
df_aux = df2[df2["DATA FINAL"].apply(lambda x: x.year) == 2012]
df_aux

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO-MES
22728,2012-01-01,2012-01-07,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,80,R$/l,2.834,0.005,2.830,2.850,0.285,0.002,2.549,0.008,2.536,2.559,0.003,2012-01
22729,2012-01-01,2012-01-07,CENTRO OESTE,GOIAS,GASOLINA COMUM,256,R$/l,2.853,0.089,2.550,3.080,0.347,0.031,2.506,0.081,2.391,2.726,0.032,2012-01
22730,2012-01-01,2012-01-07,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,137,R$/l,2.996,0.078,2.790,3.250,0.464,0.026,2.532,0.069,2.329,2.68,0.027,2012-01
22731,2012-01-01,2012-01-07,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,131,R$/l,2.728,0.147,2.530,3.048,0.33,0.054,2.398,0.056,2.295,2.55,0.023,2012-01
22732,2012-01-01,2012-01-07,NORDESTE,ALAGOAS,GASOLINA COMUM,97,R$/l,2.778,0.065,2.690,2.960,0.439,0.023,2.339,0.033,2.262,2.4367,0.014,2012-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24127,2012-12-23,2012-12-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,736,R$/l,2.877,0.115,2.549,3.799,0.357,0.040,2.52,0.058,2.335,2.7009,0.023,2012-12
24128,2012-12-23,2012-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,2376,R$/l,2.639,0.108,2.269,2.999,0.376,0.041,2.263,0.063,2.11,2.5222,0.028,2012-12
24129,2012-12-23,2012-12-29,SUL,PARANA,GASOLINA COMUM,564,R$/l,2.805,0.076,2.530,3.150,0.413,0.027,2.392,0.049,2.2336,2.595,0.02,2012-12
24130,2012-12-23,2012-12-29,SUL,RIO GRANDE DO SUL,GASOLINA COMUM,616,R$/l,2.775,0.099,2.530,3.099,0.415,0.036,2.36,0.048,2.244,2.5354,0.02,2012-12
24131,2012-12-23,2012-12-29,SUL,SANTA CATARINA,GASOLINA COMUM,386,R$/l,2.747,0.094,2.350,2.999,0.394,0.034,2.353,0.038,2.24,2.45,0.016,2012-12

In [19]:
df_aux[df_aux["REGIÃO"] == "SUL"] ["PREÇO MÉDIO REVENDA"].mean()

2.7214423076923073

#####12. Obter uma tabela contendo a variação percentual ano a ano para o estado do Rio de Janeiro

In [20]:
# pegar a ultima informação apresentada no ano para cada estado e depois filtrar o Rio de Janeiro
# criar uma coluna "MES"
# Criar uma variavel DFRIO (QUE VAI SER APENAS UM FILTRO NO ESTADO DO RIO)
# Fazer um agrupamento no ANO-MES e pegar apenas a ultima informação do estado do Rio. Por que? tem mais de uma informação no mesmo mes
# Fazer um filtro no mês 12
df2["MES"] = df2["DATA FINAL"].apply(lambda x: x.month)
df_rio = df2[df2["ESTADO"] == "RIO DE JANEIRO"]

<ipython-input-20-cc34b4e44234>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["MES"] = df2["DATA FINAL"].apply(lambda x: x.month)

In [21]:
df_month_rio = df_rio.groupby("ANO-MES") [["PREÇO MÉDIO REVENDA", "MES"]].last()

In [22]:
(df_month_rio[df_month_rio["MES"] == 12] / df_month_rio[df_month_rio["MES"] == 12].shift(1) -1) * 100

         PREÇO MÉDIO REVENDA  MES
ANO-MES
2004-12                  NaN  NaN
2005-12             9.233449  0.0
2006-12             0.917065  0.0
2007-12             0.355591  0.0
2008-12             0.984252  0.0
2009-12             1.637427  0.0
2010-12             2.032988  0.0
2011-12             7.105263  0.0
2012-12             0.982801  0.0
2013-12             6.777894  0.0
2014-12             4.361979  0.0
2015-12            20.461634  0.0
2016-12             3.625065  0.0
2017-12            13.643178  0.0
2018-12             5.804749  0.0
2019-12             3.802993  0.0
2020-12            -1.321321  0.0

#####Desafio: Criar uma tabela contendo uma serie temporal com a diferença absoluta e percentual entre os valores mais baratos e caros. Apresentando ao lado os estados na qual os maiores e menores preços foram registrados

In [23]:
# Agrupando o max e min do preço médio de revenda por ANO-MES
df_max = df2.groupby("ANO-MES").max() ["PREÇO MÉDIO REVENDA"]
df_min = df2.groupby("ANO-MES").min()["PREÇO MÉDIO REVENDA"]

idx_max = df2.groupby("ANO-MES") ["PREÇO MÉDIO REVENDA"].idxmax()
idx_min = df2.groupby("ANO-MES") ["PREÇO MÉDIO REVENDA"].idxmin()

In [24]:
df_diff = pd.DataFrame()

In [25]:
df_diff

Empty DataFrame
Columns: []
Index: []

In [26]:
df_diff["abs_diff"] = df_max - df_min
df_diff["percent_diff"] = (df_max - df_min) / df_min * 100 #colocando no formato percent
df_diff["max"] = df_max
df_diff["min"] = df_min

In [27]:
df_diff

         abs_diff  percent_diff    max    min
ANO-MES
2004-05     0.550     29.131356  2.438  1.888
2004-06     0.584     30.543933  2.496  1.912
2004-07     0.609     31.456612  2.545  1.936
2004-08     0.530     26.108374  2.560  2.030
2004-09     0.539     26.538651  2.570  2.031
...           ...           ...    ...    ...
2021-01     1.383     36.109661  5.213  3.830
2021-02     1.688     40.960932  5.809  4.121
2021-03     2.109     46.058091  6.688  4.579
2021-04     1.450     30.353779  6.227  4.777
2021-05     1.391     28.580234  6.258  4.867

[204 rows x 4 columns]

In [28]:
df2.loc[idx_max, :] ["ESTADO"].values # FAZER ISSO PORQUE O INDICE NAO ESTÁ IGUAL, POREM OS VALORES SIM

array(['ACRE', 'MATO GROSSO', 'ACRE', 'MATO GROSSO', 'ACRE',
       'MATO GROSSO', 'MATO GROSSO', 'MATO GROSSO', 'MATO GROSSO',
       'MATO GROSSO', 'MATO GROSSO', 'MATO GROSSO', 'MATO GROSSO',
       'MATO GROSSO', 'MATO GROSSO', 'MATO GROSSO', 'MATO GROSSO',
       'MATO GROSSO', 'MATO GROSSO', 'MATO GROSSO', 'MATO GROSSO',
       'MATO GROSSO', 'MATO GROSSO', 'MATO GROSSO', 'ACRE', 'ACRE',
       'RORAIMA', 'RORAIMA', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'MATO GROSSO', 'MATO GROSSO', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'MATO GROSSO', 'MATO GROSSO', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'RIO DE JANEIRO', 'ACRE', 'ACRE', 'ACRE', 'RIO DE JANEIRO',
       'RIO DE JANEIRO', 'RIO DE JANEIRO', 'RIO DE JANEIRO',
       'RIO DE JANEIRO', 'RIO DE JANEIRO', 'RIO DE JANEIRO',
       'RIO DE JANEIRO', 'RIO DE JANEIRO', 'RIO DE JANEIRO', 'ACRE',
       'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE', 'ACRE',
       'ACRE', 'ACRE'], dtype=object)

In [29]:
df_diff["ESTADO_MAX"] = df2.loc[idx_max, :] ["ESTADO"].values
df_diff["ESTADO_MIN"] = df2.loc[idx_min, :] ["ESTADO"].values

In [30]:
df_diff

         abs_diff  percent_diff    max    min   ESTADO_MAX        ESTADO_MIN
ANO-MES
2004-05     0.550     29.131356  2.438  1.888         ACRE         SAO PAULO
2004-06     0.584     30.543933  2.496  1.912  MATO GROSSO         SAO PAULO
2004-07     0.609     31.456612  2.545  1.936         ACRE  DISTRITO FEDERAL
2004-08     0.530     26.108374  2.560  2.030  MATO GROSSO         SAO PAULO
2004-09     0.539     26.538651  2.570  2.031         ACRE         SAO PAULO
...           ...           ...    ...    ...          ...               ...
2021-01     1.383     36.109661  5.213  3.830         ACRE             AMAPA
2021-02     1.688     40.960932  5.809  4.121         ACRE             AMAPA
2021-03     2.109     46.058091  6.688  4.579         ACRE             AMAPA
2021-04     1.450     30.353779  6.227  4.777         ACRE             AMAPA
2021-05     1.391     28.580234  6.258  4.867         ACRE             AMAPA

[204 rows x 6 columns]

In [31]:
# ESTADO COM O MAIOR PREÇO

df_diff["ESTADO_MAX"].value_counts()

ACRE              166
MATO GROSSO        25
RIO DE JANEIRO     11
RORAIMA             2
Name: ESTADO_MAX, dtype: int64

In [32]:
# ESTADO COM MENOR PREÇO

df_diff["ESTADO_MIN"].value_counts()

SAO PAULO              40
AMAPA                  38
PIAUI                  28
PARAIBA                28
PARANA                 14
AMAZONAS               14
DISTRITO FEDERAL       12
MARANHAO                9
SANTA CATARINA          6
PERNAMBUCO              4
MATO GROSSO DO SUL      3
RIO GRANDE DO NORTE     2
GOIAS                   2
CEARA                   2
BAHIA                   2
Name: ESTADO_MIN, dtype: int64